export const SEO_KEYWORDS = [
  "AI career dashboard",
  "resume analyzer",
  "career strategy",
  "resume checker",
  "AI resume builder",
  "cover letter generator",
  "skill gap analysis",
  "job application tools",
  "career assistant",
  "ATS optimization",
  "professional development",
  "UdyatAI",
  "AI career guide",
  "resume improvement",
  "job search tools",
  "career growth",
  "AI-powered resume",
  "career insights",
  "job application optimization",
  "AI career coach",
  "resume feedback",
  "career planning",
  "job market analysis",
  "AI job search",
  "resume tips",
  "career advice",
  "AI resume analysis",
  "job application success",
  "AI career tools",
  "resume optimization",
  "career enhancement",
  "AI-driven career",
  "resume insights",
  "job application strategies",
  "AI career insights",
  "resume evaluation",
  "career advancement",
  "AI resume tips",
  "job application improvement",
  "AI career development",
  "resume skills analysis",
  "career resume builder",
  "AI cover letter",
  "resume writing assistant",
  "career resume analysis",
  "AI job application",
  "resume career guide",
  "AI resume feedback",
  "career resume optimization",
];
